### ISSUE TITLE
LeGo_Cursor miss the dependency of LeGo_EventHandler ?

### ISSUE THREAD

**Issue by skydivin4ng3l** [Lehona/LeGo#16] opened 2019-10-20 10:58 UTC
https://github.com/Lehona/LeGo/blob/f16e02592aa86be5392dc3cb3f255dbf37e3dcce/LeGo.d#L62

**Comment by skydivin4ng3l** [comment] 2019-10-20 11:05
also with
`if(f & LeGo_Cursor)         { f = f | LeGo_EventHandler | LeGo_Interface | LeGo_View; };`

Cursor_Event seems to be uninitialized meaning 0. 
So for example
`Event_Has(Cursor_Event, someListener)`
will fail.

**Comment by szapp** [comment] 2019-10-20 11:17
LeGo_EventHandler does not require any initialization. You seem to have missed the idea of the cursor event. It allows to register functions with the event handler. These functions will be called on different mouse events with a corresponding function argument. See [this example](https://lego.worldofplayers.de/?Beispiele_Cursor#Effektivere%20Verwendung%20mit%20dem%20EventHandler) to get the idea.

I will close this issue. Let me know if I misunderstood the issue here.

**Closed as completed by szapp** 2019-10-20 11:17 UTC

**Comment by skydivin4ng3l** [comment] 2019-10-20 11:38
You misunderstood. 
Cursor_Event should not be 0 after
[this](https://github.com/Lehona/LeGo/blob/f16e02592aa86be5392dc3cb3f255dbf37e3dcce/LeGo.d#L160) or am I wrong? I am using it exactly as in the example.

**Comment by szapp** [comment] 2019-10-20 11:42
The package requires initialization from a new game. If you add this package later on and load a game that was saved without, it won't be initialized.

**Comment by skydivin4ng3l** [comment] 2019-10-20 11:44
good to know, although the function gets called,... would be nice to have some Info about such behavior in the Wiki, are there other Flags that have similar behavior?

**Comment by szapp** [comment] 2019-10-20 11:55
There seems to be no such information, because LeGo was designed with the intention to be used with mods that the player will start with a new game. Regardless of LeGo, in Gothic scripting it is common practice and highly recommended to always to start a new game to check script changes.  
This should never be an issue. The reason you mentioned why you load a game to test your scripts is because the hero is not initialized during Init_Global on creating a new game. You can add this:

```C++
func void Init_Global() {

    // ...

    FF_ApplyExt(my_stuff, 1, 1);
};
```

This runs the function `my_stuff` once after the game timer started (= after the hero was created). Alternatively, you can skip any action requiring the hero with 

```C++
if (Hlp_IsValidNpc(hero)) {
    // Hero exists
};
````

**Comment by skydivin4ng3l** [comment] 2019-10-20 11:58
the other reason I use Load game is,...new game takes for ever,...alone loading a save takes for ever with zSpy level 1

But thank you for the tip on the start up, will try that out!

**Comment by szapp** [comment] 2019-10-20 12:05
Two hints:

- Use a minimal test level without any vobs
- Minimizing the zSpy speeds up everything

**Comment by skydivin4ng3l** [comment] 2019-10-20 12:06
is there a tutorial about this somewhere?

**Comment by szapp** [comment] 2019-10-20 12:12
About these tricks? No, this is stuff you pick up in the World of Players forum in the World of Gothic Editing section.
